/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ParceirosRouteImport } from './routes/parceiros'
import { Route as FornecedoresRouteImport } from './routes/fornecedores'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ParceiroLoginRouteImport } from './routes/parceiro.login'
import { Route as ParceiroDashboardRouteImport } from './routes/parceiro.dashboard'

const ParceirosRoute = ParceirosRouteImport.update({
  id: '/parceiros',
  path: '/parceiros',
  getParentRoute: () => rootRouteImport,
} as any)
const FornecedoresRoute = FornecedoresRouteImport.update({
  id: '/fornecedores',
  path: '/fornecedores',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ParceiroLoginRoute = ParceiroLoginRouteImport.update({
  id: '/parceiro/login',
  path: '/parceiro/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ParceiroDashboardRoute = ParceiroDashboardRouteImport.update({
  id: '/parceiro/dashboard',
  path: '/parceiro/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/fornecedores': typeof FornecedoresRoute
  '/parceiros': typeof ParceirosRoute
  '/parceiro/dashboard': typeof ParceiroDashboardRoute
  '/parceiro/login': typeof ParceiroLoginRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/fornecedores': typeof FornecedoresRoute
  '/parceiros': typeof ParceirosRoute
  '/parceiro/dashboard': typeof ParceiroDashboardRoute
  '/parceiro/login': typeof ParceiroLoginRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/fornecedores': typeof FornecedoresRoute
  '/parceiros': typeof ParceirosRoute
  '/parceiro/dashboard': typeof ParceiroDashboardRoute
  '/parceiro/login': typeof ParceiroLoginRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/fornecedores'
    | '/parceiros'
    | '/parceiro/dashboard'
    | '/parceiro/login'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/fornecedores'
    | '/parceiros'
    | '/parceiro/dashboard'
    | '/parceiro/login'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/fornecedores'
    | '/parceiros'
    | '/parceiro/dashboard'
    | '/parceiro/login'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  FornecedoresRoute: typeof FornecedoresRoute
  ParceirosRoute: typeof ParceirosRoute
  ParceiroDashboardRoute: typeof ParceiroDashboardRoute
  ParceiroLoginRoute: typeof ParceiroLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/parceiros': {
      id: '/parceiros'
      path: '/parceiros'
      fullPath: '/parceiros'
      preLoaderRoute: typeof ParceirosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fornecedores': {
      id: '/fornecedores'
      path: '/fornecedores'
      fullPath: '/fornecedores'
      preLoaderRoute: typeof FornecedoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parceiro/login': {
      id: '/parceiro/login'
      path: '/parceiro/login'
      fullPath: '/parceiro/login'
      preLoaderRoute: typeof ParceiroLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parceiro/dashboard': {
      id: '/parceiro/dashboard'
      path: '/parceiro/dashboard'
      fullPath: '/parceiro/dashboard'
      preLoaderRoute: typeof ParceiroDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  FornecedoresRoute: FornecedoresRoute,
  ParceirosRoute: ParceirosRoute,
  ParceiroDashboardRoute: ParceiroDashboardRoute,
  ParceiroLoginRoute: ParceiroLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
